#######################
# DyTox, for CIFAR100 #
#######################

# Model definition
model: resmoe_tiny_patch16_224_expert8_attn_loss_convit
drop: 0.0
input_size: 224
starting_threshold_dense: 0.9
target_threshold_dense: 0.5
starting_threshold_moe: 0.9
target_threshold_moe: 0.5
local_up_to_layer: 5
class_attention: true

# Training setting
no_amp: true
eval_every: 50

# Base hyperparameter
weight_decay: 0.000001
batch_size: 256
incremental_batch_size: 256
incremental_lr: 0.0002
rehearsal: icarl_all

# Knowledge Distillation
auto_kd: true

# Finetuning
finetuning: balanced
finetuning_epochs: 20
ft_no_sampling: true

# Dytox model
dytox: true
freeze_task: [old_task_tokens, old_heads]
freeze_ft: [sab]

# Divergence head to get diversity
head_div: 0.1
head_div_mode: tr

# Independent Classifiers
ind_clf: 1-1
bce_loss: true


# Advanced Augmentations, here disabled

## Erasing
reprob: 0.0
remode: pixel
recount: 1
resplit: false

## MixUp & CutMix
mixup: 0.0
cutmix: 0.0
